### PR TITLE
Added babelify deps for easier consumption

### PR DESCRIPTION
**Pull request by CodeBaboon**

### CODE REVIEW

**Comment by CodeBaboon** [comment]
@dbatiste @dlockhart @omsmith Anyone cool with reviewing/merging this?

**Comment by omsmith** [comment]
LGTM, makes sense for the intention

**Comment by CodeBaboon** [comment]
Thanks @omsmith !

**Comment by dlockhart** [comment]
Looks good, thanks for fixing this.

**Pull request merged**
